name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup stdlib
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --yes libstdc++-15-dev
      - name: Setup clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: ${{ matrix.os }}-package-${{ hashFiles('xmake.lua') }}
          build-cache: true
          build-cache-key: ${{ matrix.os }}-build-${{ hashFiles('xmake.lua') }}
      - name: Configure
        run: xmake config --yes --toolchain=clang
      - name: Build
        run: xmake build --yes
      - name: Install
        run: xmake install --yes --installdir=./package
      - name: Package for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir dist
          tar --create --xz --file dist/${{ github.event.repository.name }}-linux.tar.xz --directory ./package .
      - name: Package for windows
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory dist
          Compress-Archive -Path ./package/* -DestinationPath dist/${{ github.event.repository.name }}-windows.zip
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}
          path: dist/*
          archive: false
          retention-days: 1
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ github.event.repository.name }}-*
          path: dist
          archive: false
          merge-multiple: true
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" dist/* --generate-notes
